# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29012bcd1d13daafae44436fd0a2b026416fe684b7b57efb79d79331584b80766136236bf3d29d59a568119ee30a2f0f99d2eacb0aa39e3c0514a4659ecc2a65

test:
  secret_key_base: 15385f535cf1a67c4ca3d5149dac51272a99ac9621683351be14c7a3ff085dfaa1838ae1c3893c1b41f27e449891418987d96913f263089d4b2be7fefae319bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
